//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StadiumEngine.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Notifications {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notifications() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("StadiumEngine.Common.Resources.Notifications", typeof(Notifications).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string access_code {
            get {
                return ResourceManager.GetString("access_code", resourceCulture);
            }
        }
        
        public static string booking_confirmation {
            get {
                return ResourceManager.GetString("booking_confirmation", resourceCulture);
            }
        }
        
        public static string booking_confirmation_locker_room {
            get {
                return ResourceManager.GetString("booking_confirmation_locker_room", resourceCulture);
            }
        }
        
        public static string password_notification_user_created {
            get {
                return ResourceManager.GetString("password_notification_user_created", resourceCulture);
            }
        }
        
        public static string password_notification_user_reset {
            get {
                return ResourceManager.GetString("password_notification_user_reset", resourceCulture);
            }
        }
        
        public static string password_notification_customer_created {
            get {
                return ResourceManager.GetString("password_notification_customer_created", resourceCulture);
            }
        }
        
        public static string password_notification_customer_reset {
            get {
                return ResourceManager.GetString("password_notification_customer_reset", resourceCulture);
            }
        }
    }
}
